# Generated by Django 2.2.3 on 2019-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('nominal', models.IntegerField(max_length=8)),
                ('currency_name', models.CharField(max_length=30)),
                ('rate', models.FloatField(max_length=8)),
                ('changes', models.FloatField(max_length=8)),
                ('procent', models.CharField(max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
